name: Show latest tweet

on:
  push:
#     branches: [ master ]
#   schedule:
#     - cron: '0 * * * *'
      
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_github('gadenbuie/tweetrmd')"
          Rscript -e "remotes::install_github('rstudio/webshot2')"
          Rscript -e "install.packages('rtweet')"
      - name: Run script
        env:
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        run: |-
          Rscript -e "source('twitter.R')"
      - name: Commit results
        run: |
          git add tweet.png && git commit -m "Update latest tweet" || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
